version: '3'
services:
  # RabbitMQ service
  rabbitmq:
    image: "rabbitmq:management"  # RabbitMQ with management plugin
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672" # RabbitMQ management UI (optional)
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persist RabbitMQ data

  # Node.js backend service
  nodejs:
    build:
      context: .
      dockerfile: dockerfile
    container_name: ride-open
    ports:
      - "3002:3002"
    environment:
      - RABBITMQ_URL=rabbitmq://rabbitmq:5672  # For internal RabbitMQ communication
       # Expose the port for the Node.js app
    depends_on:
      - rabbitmq
    volumes:
      - ./src:/app/src

volumes:
  rabbitmq_data:
