services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  app:
    build:
      context: .
    container_name: ride
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://localhost:15673 # Use rabbitmq as the hostname, not localhost
