name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/my_ec2_key
        chmod 600 ~/.ssh/my_ec2_key
        # Ensure the known_hosts file is set up correctly
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
      env:
        EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: pawan042/openride:latest

    - name: Deploy to Server
      run: |
        ssh -i ~/.ssh/my_ec2_key -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          # Pull the latest image
          docker pull pawan042/openride:latest
          
          # Shut down old containers
          docker-compose down
          
          # Start the container with PM2
          # Check if the container with the name 'ride' exists
          if pm2 show ride > /dev/null 2>&1; then
            # If it exists, reload the container
            pm2 reload ride
          else
            # If it doesn't exist, start a new container with PM2
            pm2 start docker-compose.yml --name ride
          fi
        EOF
